import { type ApiMeta, type Params } from "./types.ts";

const typesMap: Record<string, string> = {
   Array: "unknown[]",
   Boolean: "boolean",
   Buffer: "number",
   Dict: "Record<string, unknown>",
   Dictionary: "Record<string, unknown>",
   Float: "number",
   Integer: "number",
   LuaRef: "unknown",
   Object: "unknown",
   String: "string",
   Tabpage: "number",
   void: "void",
   Window: "number",
};

export function toTypescriptType(type: string): string {
   const mapped = typesMap[type];
   if (mapped) return mapped;

   // ArrayOf(String) => string[]
   // ArrayOf(Integer, 2) => [number, number]
   const arrayOf = /^ArrayOf\((\w+)(?:,\s*(\d+))?\)$/.exec(type);
   if (arrayOf?.[1]) {
      const item = toTypescriptType(arrayOf[1]);
      if (arrayOf[2]) {
         const length = Number(arrayOf[2]);
         return `[${Array.from({ length }, () => item).join(", ")}]`;
      }
      return `${item}[]`;
   }

   console.warn(`unknown neovim type "${type}", falling back to "unknown"`);
   return "unknown";
}

function parseParameters(params: Params) {
   return params.map((param) => `${param[1]}: ${toTypescriptType(param[0])}`).join(", ");
}

export function generateTypescriptContent(neovimApi: ApiMeta) {
   let output = `/* oxlint-disable typescript/no-invalid-void-type */

/*
 * file generated by bunvim: https://github.com/wallpants/bunvim
 */

import { type EventsMap } from "bunvim";

export type NeovimApi<
  Notifications extends EventsMap = EventsMap,
  Requests extends EventsMap = EventsMap,
> = {\n`;
   // functions
   output += "  functions: {\n";
   neovimApi.functions.forEach((fun) => {
      if (fun.deprecated_since !== undefined) {
         output += `    /** @deprecated since api level ${fun.deprecated_since} */\n`;
      }
      output += `    ${fun.name}: {
      parameters: [${parseParameters(fun.parameters)}];
      return_type: ${toTypescriptType(fun.return_type)};\n    };\n`;
   });
   output += "  };\n\n";

   // ui_events
   output += "  ui_events: {\n";
   neovimApi.ui_events.forEach((event) => {
      output += `    ${event.name}: {\n      parameters: [${parseParameters(
         event.parameters,
      )}];\n    };\n`;
   });
   output += "  };\n\n";

   // error_types
   output += "  error_types: {\n";
   Object.entries(neovimApi.error_types).forEach(([type, { id }]) => {
      output += `    ${type}: { id: ${id}; };\n`;
   });
   output += "  };\n\n";

   // types
   output += "  types: {\n";
   Object.entries(neovimApi.types).forEach(([type, { id, prefix }]) => {
      output += `    ${type}: { id: ${id}; prefix: "${prefix}"; };\n`;
   });
   output += "  };\n\n";

   // ui_options
   output += `  ui_options: ${JSON.stringify(neovimApi.ui_options)};\n\n`;

   // custom user notifications
   output += `  notifications: Notifications;\n\n`;

   // custom user requests
   output += `  requests: Requests;\n`;

   output += "};";

   return output;
}
